version: "2"
services:

  base:
    build: .
    command: bash -c "mbs-upgradedb && touch /etc/module-build-service/.ready"
    volumes:
      - ./:/tmp/module_build_service:z
      - /etc/module-build-service
      - /tmp/module_build_service/module_build_service.egg-info

  fedmsg-relay:
    depends_on:
      - base
    build: .
    command: bash -c "while [ ! -f /etc/module-build-service/.ready ] ; do sleep 1 ; done ; fedmsg-relay"
    expose:
      - 2001
      - 2003
    volumes_from:
      - base

  scheduler:
    depends_on:
      - base
    build: .
    command: bash -c "while [ ! -f /etc/module-build-service/.ready ] ; do sleep 1 ; done ; fedmsg-hub"
    links:
      - fedmsg-relay
    volumes_from:
      - base

  frontend:
    depends_on:
      - base
    build: .
    command: bash -c "while [ ! -f /etc/module-build-service/.ready ] ; do sleep 1 ; done ; mbs-frontend"
    ports:
      - "5000:5000"
    links:
      - scheduler
      - fedmsg-relay
    volumes_from:
      - base
