version: "2"
services:

  fedmsg-relay:
    build: .
    command: fedmsg-relay
    expose:
      - 2001
      - 2003
    volumes:
      # module_build_service sources are bind-mounted, so you don't have to rebuild
      - ./:/opt/module_build_service/:z

  scheduler:
    build: .
    command: python2 /opt/module_build_service/module_build_service_daemon.py
    links:
      - fedmsg-relay
    environment:
      # Check /var/tmp/krbcc and make sure that it is not a directory.  If it
      # is, then delete it with 'sudo rm -rf /var/tmp/krbcc'.
      # Initialize the file before running 'docker-compose up' with:
      # $ KRB5CCNAME=FILE:/var/tmp/krbcc kinit YOUR_USERNAME@FEDORAPROJECT.ORG
      - KRB5CCNAME=FILE:/var/tmp/krbcc
    volumes:
      # module_build_service sources are bind-mounted, so you don't have to rebuild
      - ./:/opt/module_build_service/:z
      - /var/tmp/krbcc:/var/tmp/krbcc:Z

  frontend:
    build: .
    ports:
      - "5000:5000"
    links:
      - scheduler
      - fedmsg-relay
    depends_on:
      - upgradedb
      - generatelocalhostcert
    volumes:
      # module_build_service sources are bind-mounted, so you don't have to rebuild
      - ./:/opt/module_build_service/:z
    command: python2 manage.py runssl

  upgradedb:
    build: .
    volumes:
      - ./:/opt/module_build_service/:z
    command: python2 manage.py upgradedb

  generatelocalhostcert:
    build: .
    volumes:
      - ./:/opt/module_build_service/:z
    command: python2 manage.py generatelocalhostcert
