version: "2"
services:
  module_build_service_daemon:
    build:
      context: .
    command: python2 /opt/module_build_service/module_build_service_daemon.py
    volumes:
      - ./module_build_service/:/opt/module_build_service/module_build_service/:Z  # module_build_service sources are bind-mounted, so you don't have to rebuild
      - ~/.fedora.cert:/root/.fedora.cert:Z   # koji credentials are mounted inside
      - ~/.fedora-server-ca.cert:/root/.fedora-server-ca.cert:Z
      - ~/.fedora-upload-ca.cert:/root/.fedora-upload-ca.cert:Z
  module_build_service:
    build:
      context: .
    ports:
      - "5000:5000"
    links:
      - module_build_service_daemon
    volumes:
      - ./module_build_service/:/opt/module_build_service/module_build_service/:Z
