# Template to produce a new OpenShift pipeline job for triggering a build on repotracker messages
#
---
apiVersion: v1
kind: Template
metadata:
  name: mbs-repotracker-trigger
labels:
  template: mbs-repotracker-trigger
parameters:
- name: NAME
  displayName: Short unique identifier for the templated instances
  description: This field is used to deploy multiple pipelines to one OpenShift project from this template.
  value: mbs-repotracker-trigger
- name: MBS_GIT_REPO
  displayName: MBS Git repo URL
  description: Default MBS Git repo URL in which to run dev tests against
  value: "https://pagure.io/fm-orchestrator.git"
- name: MBS_GIT_REF
  displayName: MBS Git repo ref
  description: Default MBS Git repo ref in which to run dev tests against
  value: master
- name: TRACKED_CONTAINER_REPO
  displayName: Container repo to be tracked
  value: quay.io/factory2/mbs-frontend
- name: TRACKED_TAG
  displayName: Name of tag to be tracked
  required: true
- name: MBS_BACKEND_REPO
  displayName: The location of the repo (without tag) where the mbs-backend image is located
  value: quay.io/factory2/mbs-backend
- name: CONTAINER_REGISTRY_CREDENTIALS
  displayName: Secret name of container registries used for pulling and pushing images
  value: factory2-pipeline-registry-credentials
  required: false
- name: JENKINS_AGENT_IMAGE
  displayName: Container image for Jenkins slave pods
  value: quay.io/factory2/mbs-jenkins-slave:latest
- name: JENKINS_AGENT_CLOUD_NAME
  displayName: Name of OpenShift cloud in Jenkins master configuration
  value: openshift
- name: MESSAGING_PROVIDER
  displayName: Name of the JMS messaging provider
  value: Red Hat UMB
- name: MESSAGING_TOPIC
  displayName: Name of the topic that the trigger subscribes to
  value: "Consumer.rh-jenkins-ci-plugin.c3i-mbs-repotracker-trigger.VirtualTopic.eng.repotracker.container.tag.>"
- name: TEST_JOB_NAME
  displayName: Name of integration test job to trigger
  required: true
- name: TEST_JOB_NAMESPACE
  displayName: Namespace in which to trigger the integration test job
  required: false
- name: USE_C3IAAS
  displayName: >-
    Use C3I-as-a-Service to dynamically allocate a temporary OpenShift project for building
    and testing.
  required: true
  value: "true"
- name: C3IAAS_REQUEST_PROJECT_BUILD_CONFIG_NAMESPACE
  displayName: The namespace where the C3I-as-a-Service project request BuildConfig has been defined
  required: false
  value: c3i
- name: C3IAAS_REQUEST_PROJECT_BUILD_CONFIG_NAME
  displayName: The name of the C3I-as-a-Service project request BuildConfig
  required: false
  value: c3iaas-request-project
- name: C3IAAS_LIFETIME
  displayName: The lifetime of the OpenShift project allocated by C3I-as-a-Service.
  required: true
  value: "120"
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: "${NAME}-jenkins-slave"
    labels:
      app: "${NAME}"
- kind: RoleBinding
  apiVersion: v1
  metadata:
    name: "${NAME}-jenkins-slave_edit"
    labels:
      app: "${NAME}"
  subjects:
  - kind: ServiceAccount
    name: "${NAME}-jenkins-slave"
  roleRef:
    name: edit
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    runPolicy: "Serial"
    completionDeadlineSeconds: 1800
    source:
      git:
        uri: "${MBS_GIT_REPO}"
        ref: "${MBS_GIT_REF}"
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        env:
        - name: JENKINS_AGENT_CLOUD_NAME
          value: "${JENKINS_AGENT_CLOUD_NAME}"
        - name: JENKINS_AGENT_IMAGE
          value:  "${JENKINS_AGENT_IMAGE}"
        - name: JENKINS_AGENT_SERVICE_ACCOUNT
          value: "${NAME}-jenkins-slave"
        - name: TRACKED_CONTAINER_REPO
          value: "${TRACKED_CONTAINER_REPO}"
        - name: TRACKED_TAG
          value: "${TRACKED_TAG}"
        - name: MBS_BACKEND_REPO
          value: "${MBS_BACKEND_REPO}"
        - name: CONTAINER_REGISTRY_CREDENTIALS
          value: "${CONTAINER_REGISTRY_CREDENTIALS}"
        - name: TEST_JOB_NAME
          value: "${TEST_JOB_NAME}"
        - name: TEST_JOB_NAMESPACE
          value: "${TEST_JOB_NAMESPACE}"
        - name: USE_C3IAAS
          value: "${USE_C3IAAS}"
        - name: C3IAAS_REQUEST_PROJECT_BUILD_CONFIG_NAMESPACE
          value: "${C3IAAS_REQUEST_PROJECT_BUILD_CONFIG_NAMESPACE}"
        - name: C3IAAS_REQUEST_PROJECT_BUILD_CONFIG_NAME
          value: "${C3IAAS_REQUEST_PROJECT_BUILD_CONFIG_NAME}"
        - name: C3IAAS_LIFETIME
          value: "${C3IAAS_LIFETIME}"
        - name: MESSAGING_PROVIDER
          value: "${MESSAGING_PROVIDER}"
        - name: MESSAGING_TOPIC
          value: "${MESSAGING_TOPIC}"
        # CI_MESSAGE and MESSAGE_HEADERS are used internally by JMS messaging plugin
        - name: CI_MESSAGE
          value:
        - name: MESSAGE_HEADERS
          value:
        jenkinsfilePath: openshift/integration/koji/pipelines/templates/mbs-repotracker-trigger.Jenkinsfile
