# Template to produce a new OpenShift pipeline job for triggering a build on repotracker messages
#
---
apiVersion: v1
kind: Template
metadata:
  name: mbs-greenwave-trigger
labels:
  template: mbs-greenwave-trigger
parameters:
- name: NAME
  displayName: Short unique identifier for the templated instances
  description: This field is used to deploy multiple pipelines to one OpenShift project from this template.
  required: true
- name: MBS_GIT_REPO
  displayName: MBS Git repo URL
  description: Default MBS Git repo URL in which to run dev tests against
  value: "https://pagure.io/fm-orchestrator.git"
- name: MBS_GIT_REF
  displayName: MBS Git repo ref
  description: Default MBS Git repo ref in which to run dev tests against
  value: master
- name: DECISION_CONTEXT_REGEX
  displayName: Regex pattern for Greenwave decision context in CI message
  required: true
- name: SUBJECT_IDENTIFIER_REGEX
  displayName: Regex pattern for Greenwave subject identifier in CI message
  required: true
- name: SOURCE_CONTAINER_REPO
  displayName: Container repo of the image
  required: true
- name: TARGET_TAG
  displayName: Tag name to promote the image to
  required: true
- name: IMAGE_PROMOTION_JOB
  displayName: Downstream image promotion job to trigger
  required: true
- name: MESSAGING_PROVIDER
  displayName: Name of the JMS messaging provider
  value: Red Hat UMB
- name: MESSAGING_TOPIC
  displayName: Name of the topic that the trigger subscribes to
  value: "Consumer.rh-jenkins-ci-plugin.c3i-greenwave-trigger.VirtualTopic.eng.greenwave.decision.update"
- name: JENKINS_AGENT_IMAGE
  displayName: Container image for Jenkins slave pods
  value: quay.io/factory2/mbs-jenkins-slave:latest
- name: JENKINS_AGENT_CLOUD_NAME
  displayName: Name of OpenShift cloud in Jenkins master configuration
  value: openshift
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: "${NAME}-jenkins-slave"
    labels:
      app: "${NAME}"
- kind: RoleBinding
  apiVersion: v1
  metadata:
    name: "${NAME}-jenkins-slave_edit"
    labels:
      app: "${NAME}"
  subjects:
  - kind: ServiceAccount
    name: "${NAME}-jenkins-slave"
  roleRef:
    name: edit
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    runPolicy: "Serial"
    completionDeadlineSeconds: 1800
    source:
      git:
        uri: "${MBS_GIT_REPO}"
        ref: "${MBS_GIT_REF}"
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        env:
        - name: JENKINS_AGENT_CLOUD_NAME
          value: "${JENKINS_AGENT_CLOUD_NAME}"
        - name: JENKINS_AGENT_IMAGE
          value:  "${JENKINS_AGENT_IMAGE}"
        - name: JENKINS_AGENT_SERVICE_ACCOUNT
          value: "${NAME}-jenkins-slave"
        - name: SOURCE_CONTAINER_REPO
          value: "${SOURCE_CONTAINER_REPO}"
        - name: TARGET_TAG
          value: "${TARGET_TAG}"
        - name: IMAGE_PROMOTION_JOB
          value: "${IMAGE_PROMOTION_JOB}"
        - name: DECISION_CONTEXT_REGEX
          value: "${DECISION_CONTEXT_REGEX}"
        - name: SUBJECT_IDENTIFIER_REGEX
          value: "${SUBJECT_IDENTIFIER_REGEX}"
        - name: MESSAGING_PROVIDER
          value: "${MESSAGING_PROVIDER}"
        - name: MESSAGING_TOPIC
          value: "${MESSAGING_TOPIC}"
        # CI_MESSAGE and MESSAGE_HEADERS are used internally by JMS messaging plugin
        - name: CI_MESSAGE
          value:
        - name: MESSAGE_HEADERS
          value:
        jenkinsfilePath: openshift/integration/koji/pipelines/templates/mbs-greenwave-trigger.Jenkinsfile
